name: proj001_lfb
channels:
  - r
  - defaults
dependencies:
  - alabaster=0.7.10=py35h6fb19ab_0
  - asn1crypto=0.24.0=py35_0
  - babel=2.5.3=py35_0
  - backcall=0.1.0=py35_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.1.18=py35_0
  - cffi=1.11.5=py35h9745a5d_0
  - chardet=3.0.4=py35hb6e9ddf_1
  - cryptography=2.2.2=py35h14c3975_0
  - cycler=0.10.0=py35hc4d5149_0
  - dbus=1.13.2=hc3f9b76_0
  - decorator=4.2.1=py35_0
  - docutils=0.14=py35hd11081d_0
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - glib=2.53.6=h5d9569c_2
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - icu=58.2=h9c2bf20_1
  - idna=2.6=py35h8605a33_1
  - imagesize=1.0.0=py35_0
  - intel-openmp=2018.0.0=8
  - ipykernel=4.8.2=py35_0
  - ipython=6.3.1=py35_0
  - ipython_genutils=0.2.0=py35hc9e07d0_0
  - jedi=0.11.1=py35_1
  - jinja2=2.10=py35h480ab6d_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=5.2.3=py35_0
  - jupyter_core=4.4.0=py35ha89e94b_0
  - kiwisolver=1.0.1=py35hcb1117a_0
  - krb5=1.16=h3f6afd0_6
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libpng=1.6.34=hb9fc6fc_0
  - libpq=10.3=h1ad7b7a_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libxcb=1.13=h1bed415_0
  - libxml2=2.9.8=hf84eae3_0
  - markupsafe=1.0=py35h4f4fcf6_1
  - matplotlib=2.2.2=py35h0e671d2_1
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py35h3010b51_0
  - mkl_random=1.0.1=py35h629b387_0
  - ncurses=6.0=h9df7e31_2
  - numpy=1.14.2=py35hdbf6ddf_1
  - numpydoc=0.8.0=py35_0
  - openssl=1.0.2o=h20670df_0
  - packaging=17.1=py35_0
  - pandas=0.22.0=py35hf484d3e_0
  - parso=0.1.1=py35h1b200a3_0
  - patsy=0.5.0=py35_0
  - pcre=8.41=hc27e229_1
  - pexpect=4.4.0=py35_0
  - pickleshare=0.7.4=py35hd57304d_0
  - pip=9.0.3=py35_0
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - psycopg2=2.7.4=py35hb7f436b_0
  - ptyprocess=0.5.2=py35h38ce0a3_0
  - pycparser=2.18=py35h61b3040_1
  - pygments=2.2.0=py35h0f41973_0
  - pyopenssl=17.5.0=py35h4f8b8c8_0
  - pyparsing=2.2.0=py35h041ed72_1
  - pyqt=5.9.2=py35h751905a_0
  - pysocks=1.6.8=py35_0
  - python=3.5.5=hc3d631a_1
  - python-dateutil=2.7.2=py35_0
  - pytz=2018.3=py35_0
  - pyzmq=17.0.0=py35h14c3975_0
  - qt=5.9.4=h4e5bff0_0
  - readline=7.0=ha6073c6_4
  - requests=2.18.4=py35hb9e6ad1_1
  - scipy=1.0.1=py35hfc37229_0
  - seaborn=0.8.1=py35h04cba02_0
  - setuptools=39.0.1=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.19.8=py35hf484d3e_0
  - six=1.11.0=py35h423b573_1
  - snowballstemmer=1.2.1=py35h5435977_0
  - sphinx=1.7.2=py35_0
  - sphinxcontrib=1.0=py35hcb7efd2_1
  - sphinxcontrib-websupport=1.0.1=py35h3537809_1
  - sqlalchemy=1.2.6=py35h14c3975_0
  - sqlite=3.22.0=h1bed415_0
  - statsmodels=0.8.0=py35haa9d50b_0
  - tk=8.6.7=hc745277_3
  - tornado=5.0.1=py35_1
  - traitlets=4.3.2=py35ha522a97_0
  - typing=3.6.4=py35_0
  - urllib3=1.22=py35h2ab6e29_0
  - wcwidth=0.1.7=py35hcd08066_0
  - wheel=0.31.0=py35_0
  - xz=5.2.3=h55aa19d_2
  - zeromq=4.2.3=h439df22_3
  - zlib=1.2.11=ha838bed_2
  - pip:
    - attrs==17.4.0
    - autoflake==1.1
    - autopep8==1.3.3
    - awscli==1.14.32
    - boto3==1.5.18
    - botocore==1.8.36
    - colorama==0.3.7
    - configobj==5.0.6
    - flake8==3.5.0
    - jmespath==0.9.3
    - mccabe==0.6.1
    - pew==1.1.2
    - pipenv==9.0.3
    - pluggy==0.6.0
    - py==1.5.2
    - pyasn1==0.4.2
    - pycodestyle==2.3.1
    - pyflakes==1.6.0
    - pytest==3.3.2
    - pyyaml==3.12
    - rsa==3.4.2
    - s3transfer==0.1.12
    - tox==2.9.1
    - virtualenv==15.1.0
    - virtualenv-clone==0.2.6
prefix: /app/software/anaconda3/envs/proj001_lfb
